### ISSUE TITLE
Github sync may be lost without notifying

### ISSUE THREAD

**Issue by ehausen** [waffleio/waffle.io#1983] opened 2015-06-28 19:48 UTC
- I had waffle open in chrome
- Closed my laptop -> sleep
- Opened again 30 min later
- Waffle didn't sync changes made in Github any more. I had to reload the waffle board page

**Comment by kellihsf** [comment] 2016-04-26 19:07
closing this as a duplicate of [#1656](https://github.com/waffleio/waffle.io/issues/1656). Thanks!

**Closed** 2016-04-26 19:07 UTC
Labels: duplicate
