### ISSUE TITLE
Epic progress bars disappear when a card within it closes in real time

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#3429] opened 2018-04-05 20:25 UTC
child of https://github.com/waffleio/waffle.io/issues/3316

![Screen Shot 2018-04-05 at 2.23.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5370e138ebef97b1f959c719/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f66b7191a37af110284f5f5d5ecc3c4a4356bcbbd671f3e57862804e0eef846d5b75956b44acbc874db750e9238e19d0b2ba884cd2f42f67b6d5db1063474f4dcbed5727a19141c95df449e8485cad123665e6712431.png)

**Comment by Alisuehobbs** [comment] 2018-04-10 21:50
I am unable to reproduce this in any of the environments. I tried by closing by hand in waffle, dragging, closing the issue in github, and merging with a pr. I am open to suggestions.

**Closed** 2018-04-11 14:53 UTC
Labels: bug
