### ISSUE TITLE
Focus by Collapsing Columns

### ISSUE THREAD

**Issue by noelhenson** [waffleio/waffle.io#1878] opened 2015-04-17 21:19 UTC
It would be great if individual columns could be collapsed in the same way the control column on the left can. This would help alleviate the pressure my staff can feel over too many items in a column (like our Possibles column, your Ideas column, most users' backlog column). This would also allow easier viewing of remaining columns for more complicated work flows.

**Comment by CodeMan99** [comment] 2015-04-17 21:21
Duplicate of #1873

**Comment by ashumz** [comment] 2015-04-29 14:04
@CodeMan99 is right @noelhenson - this is a duplicate of an existing issue, #1873. Please feel free to +1 that comment or subscribe to it for updates. We are planning to do this work in the future and appreciate your comments and feedback in support of the enhancement! 

All the best,

Ashley

**Closed** 2015-04-29 14:04 UTC
Labels: duplicate
