### ISSUE TITLE
Hour Tracking

### ISSUE THREAD

**Issue by mc706** [waffleio/waffle.io#1959] opened 2015-06-12 14:06 UTC
Besides just having issue weight tracking. Have the ability to add a number of hours to a ticket, possibly through the git commit. This allows to see amount of manpower over time. As well as for private repos, allows for monthly billing and invoicing. It would be nice to be able to quickly pull a report of what collaborators billed for how much and when. Then easily cut an invoice from there.

**Comment by O-Zone** [comment] 2015-10-28 13:19
This is actually an important selling point - we also need to be able to state both how many hours a given task is estimated to, and how many of those hours is already done. I can't understand why there isn't more focus on this? O_o

**Comment by O-Zone** [comment] 2015-10-28 13:27
Ahh - same as https://github.com/waffleio/waffle.io/issues/287 I guess! :)

**Comment by homeyer** [comment] 2015-10-28 14:01
Going to close this out as a duplicate of #287, thanks for making that connection @O-Zone!

**Closed by homeyer** 2015-10-28 14:01 UTC
Labels: duplicate
