### ISSUE TITLE
Image upload!

### ISSUE THREAD

**Issue by joshrosenheck** [waffleio/waffle.io#2069] opened 2015-08-26 19:22 UTC

**Comment by mpeltier6** [comment] 2015-08-26 19:23
+1

**Comment by jdl031** [comment] 2015-08-27 16:55
+1

**Comment by GabrielCTroia** [comment] 2015-09-17 16:43
+1

**Comment by specky-rum** [comment] 2015-10-02 13:50
+1

**Comment by tbezdeka** [comment] 2015-10-27 16:47
+1

**Comment by andrewvt** [comment] 2015-11-10 23:49
+1

**Comment by colinurbs** [comment] 2015-11-11 00:03
+1

**Comment by gbrand802** [comment] 2015-11-11 00:56
+1

**Comment by richrdkng** [comment] 2016-01-13 04:55
+1

**Comment by mrwaim** [comment] 2016-06-14 01:18
+1

**Comment by kellihsf** [comment] 2017-03-29 18:59
duplicate of [#846](https://github.com/waffleio/waffle.io/issues/846)

**Closed by kellihsf** 2017-03-29 18:59 UTC
Labels: idea
