### ISSUE TITLE
Connecting a closed PR to an open issue

### ISSUE THREAD

**Issue by hiscodeness** [waffleio/waffle.io#1870] opened 2015-04-12 19:01 UTC
I accidentally closed a PR before linking it to an issue (using 'resolve #nn' or 'Connects #nn'). Is there any way to link the issue at this point, so that the issue would be moved to the Done column, with both the issue and PR stacked together?

**Comment by burtonjc** [comment] 2015-05-04 15:50
Sorry for the delay on this. You can still connect it, you will have to refresh your board before you see it connected. The behavior of closing the issue is actually on GitHub's side and they don't support retroactively closing issues like this. So you would still have to manually close the issue after they are connected.

**Comment by burtonjc** [comment] 2015-05-04 15:51
I'm going to close this for now, but feel free to keep commenting on this thread if you have other questions on it.

**Comment by hiscodeness** [comment] 2015-05-05 05:20
Thanks for the response, that's a decent workaround.

**Comment by hiscodeness** [comment] 2015-05-15 20:05
Sorry to bring this up again, but this happened to me today, and I'm definitely not seeing the cards (issue+PR) getting bundled together, even though I put connects #nn from PR to issue and vice versa and keep refreshing the board. 

So what did I do? I had the thread for my merged and closed PR open in GitHub, where I added a comment "connects #issue". The reference in the comment links to the correct closed issue, but the board doesn't. There's a lonely issue in the done (closed) column, not linked to the PR. Where should I write the connects comment to make this work?

**Comment by homeyer** [comment] 2015-05-15 20:30
@hiscodeness, we only keep track of closed issues and PRs for a short amount of time. If the PR isn't on the board, we aren't able to visually link it to the issue on the board.

**Comment by hiscodeness** [comment] 2015-05-15 20:59
Sorry if I wasn't clear. The PR is visible in the done column, it is linked with two other issues. I just cannot get the one issue connected. It is an issue I forgot to link (using resolve #issue) when creating the PR.
________________________________
Lähettäjä: Andrew Homeyer<mailto:notifications@github.com>
Lähetetty: ‎15.‎5.‎2015 23:30
Vastaanottaja: waffleio/waffle.io<mailto:waffle.io@noreply.github.com>
Kopio: Jussi Mattila<mailto:jussi.mattila@combinostics.com>
Aihe: Re: [waffle.io] Connecting a closed PR to an open issue (#1870)


@hiscodeness<https://github.com/hiscodeness>, we only keep track of closed issues and PRs for a short amount of time. If the PR isn't on the board, we aren't able to visually link it to the issue on the board.

**Comment by hiscodeness** [comment] 2015-05-18 10:45
Here's a screenshot. I'm trying to connect issue number 7 to PR number 20.
![image](https://cloud.githubusercontent.com/assets/8625258/7679304/237ca9d2-fd64-11e4-9b40-aff439041b65.png)

**Comment by homeyer** [comment] 2015-05-18 14:54
@hiscodeness, can you show us what the title and description is for PR#20?

**Comment by hiscodeness** [comment] 2015-05-18 19:33
Sure, why not:
![image](https://cloud.githubusercontent.com/assets/8625258/7688412/f3b249d4-fdac-11e4-8f15-d316da787c10.png)

I edited some information out of the image in my previous comment. For example, there were more issues resolved by the PR than shown previously. Also, issue no. 7 is associated with a milestone, while the PR was not, but so is issue no. 16 which is correctly connected. Here's the done column in as it currently stands:
![image](https://cloud.githubusercontent.com/assets/8625258/7688536/cbb4dde2-fdad-11e4-805d-2117d8919ab7.png)

**Comment by ashumz** [comment] 2015-05-19 14:27
Hi hiscodeness, 

Thanks for providing that -- very helpful. It looks like you'll need to add the wording to the title of the issue (editable on the board view or in GitHub) or in the description of the issue (rather than the comments.)

You can edit the description in the card detail modal by selecting the pencil icon to edit the description (in the upper right hand corner of the description field.) If you add "resolves #7" in the description, you should be all set! We don't look at comments currently for connecting issues. 

Let me know if you still have questions! 

Ashley

**Comment by hiscodeness** [comment] 2015-05-19 17:49
@ashumz Thanks, that did the trick!

**Closed** 2015-05-21 17:16 UTC
