### ISSUE TITLE
be able to make private board publicly accessible

### ISSUE THREAD

**Issue by kmanzana** [waffleio/waffle.io#1674] opened 2014-12-22 16:04 UTC
request on [intercom](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/651508706)

**Comment by olyas** [comment] 2015-01-11 21:27
:+1:

**Comment by Dids** [comment] 2017-02-06 19:22
This would definitely nice. In my specific use-case, I'd simply want to show a public roadmap to my users, while keeping the repository private. Additionally being able to mark only some tasks as public would be a nice addition.

**Comment by kellihsf** [comment] 2018-08-16 18:39
Closing as a duplicate of [#3352](https://waffle.io/waffleio/waffle.io/cards/5a4ec58666a373001c2e39df)

**Closed by kellihsf** 2018-08-16 18:39 UTC
Labels: customer requested, duplicate, idea
