### ISSUE TITLE
Possible to add file attachments to card/issues?

### ISSUE THREAD

**Issue by jlberryhill** [waffleio/waffle.io#1721] opened 2015-01-24 16:53 UTC
It would be awesome if it were possible to attach a file to a card through Waffle web interface. Maybe possible through leveraging https://github.com/benbalter/github-uploader or other tools from http://ben.balter.com/2015/01/11/hacking-github/?

**Comment by homeyer** [comment] 2015-02-10 00:22
closing as duplicate of #846. Thanks for the links @jlberryhill!

**Closed** 2015-02-10 00:22 UTC
Labels: duplicate
