### ISSUE TITLE
Sort a column by a label

### ISSUE THREAD

**Issue by hcwiley** [waffleio/waffle.io#1816] opened 2015-03-20 20:32 UTC
Would be nice to be able to sort a column by a label. We use a point system, so it would be nice to have the columns order highest to lowest based on points

**Comment by kellihsf** [comment] 2016-04-26 17:07
closing this; duplicate of [#1851](https://github.com/waffleio/waffle.io/issues/1851)

**Closed** 2016-04-26 17:07 UTC
Labels: customer requested, duplicate
