### ISSUE TITLE
Attach files

### ISSUE THREAD

**Issue by rg-net** [waffleio/waffle.io#2406] opened 2016-02-23 23:31 UTC
Github allows issues. I'd like to be able to attach files in comments and issues via

**Comment by lloydwatkin** [comment] 2016-02-24 09:55
Yes this would be great, it means the product team (for us) can use just a single app then (rather than having to open github to add images)

**Comment by mattfletcher** [comment] 2016-02-24 13:43
Duplicate of #846

**Comment by kellihsf** [comment] 2016-02-24 22:06
hi @rg-net, 

As mentioned above,  we're already tracking this issue on #846 so we'll close this as a duplicate.  Since you've already added your +1 to the  existing issue, I won't add an additional one. Thanks!

**Closed** 2016-02-24 22:06 UTC
Labels: duplicate
