### ISSUE TITLE
More readable board UI

### ISSUE THREAD

**Issue by shouze** [waffleio/waffle.io#1052] opened 2014-06-18 10:59 UTC
## Maximum focus on readability
- Reduce number of colors
- Less/no shadows
- Better font & smaller font sizes

Here's a quick attempt:
![capture decran 2014-06-07 a 16 56 16](https://cloud.githubusercontent.com/assets/54712/3312717/53b38330-f6d7-11e3-94f8-3737b46a3247.png)

would be linked to #885 & #977

**Comment by kellihsf** [comment] 2016-04-26 21:26
closing this as a duplicate of [#855](https://waffle.io/waffleio/waffle.io/cards/53601909ebef97b1f959a894)

**Closed** 2016-04-26 21:26 UTC
Labels: customer requested
