### ISSUE TITLE
Add a  "add to bottom of queue" button

### ISSUE THREAD

**Issue by bwest87** [waffleio/waffle.io#1884] opened 2015-04-22 21:26 UTC
When adding things to a column, they often get sent to the top, which can inadvertently push everything to the bottom of the queue, and you end up with a LIFO system rather than a FIFO system (which is what we want). Granted, you could simply scroll all the way down and put the issue there, but that's way harder than just dragging it over, so everyone just ends up dragging it over and putting it on top.

**Comment by JeremybellEU** [comment] 2015-04-25 12:54
+1

**Comment by CodeMan99** [comment] 2015-05-07 20:58
Duplicate of #1874 ?

**Comment by homeyer** [comment] 2015-05-07 21:04
Yep, let's track this on #1874. Thanks @CodeMan99!

**Closed by homeyer** 2015-05-07 21:04 UTC
Labels: duplicate
