### ISSUE TITLE
investigate how we can be notified when duplicate stories are created

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1596] opened 2014-11-18 21:23 UTC
- [ ] splunk alerts?

**Comment by CodeMan99** [comment] 2015-04-04 04:59
Perhaps add a new "duplicate of #" syntax? Could stack cards like is done for "Connect to #" syntax for visual notification.

**Comment by homeyer** [comment] 2017-06-09 21:54
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Closed** 2017-06-09 21:54 UTC
