### ISSUE TITLE
Ability to Add Label when Creating User Story

### ISSUE THREAD

**Issue by AdamBCo** [waffleio/waffle.io#1784] opened 2015-02-24 17:48 UTC
As a user I would like the ability to add a label to a card when creating a user story.

**Comment by homeyer** [comment] 2015-02-24 18:02
Hey @AdamBCo! Closing this as a dupe of #1553. It's scheduled for this quarter, so should come down the pipe sometime soon.

**Closed by homeyer** 2015-02-24 18:02 UTC
Labels: duplicate
