### ISSUE TITLE
Wafflebot: allow flow customization

### ISSUE THREAD

**Issue by david-caro** [waffleio/waffle.io#3075] opened 2017-04-18 17:59 UTC
It would be amazing if you could customize the lanes, actions and triggers for the wafflebot. That will allow to adapt it to any development workflow.

**Comment by homeyer** [comment] 2017-06-09 16:08
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Closed** 2017-06-09 16:08 UTC
Labels: customer requested

**Comment by chaz2k** [comment] 2018-07-11 00:30
Hi,
I want to add a Testing lane, so after the PR is merged, it should go to this lane rather than the Done lane, when the issue is marked done then it is moved to the Done Column.
