### ISSUE TITLE
Granular metrics for issues' "time in state"

### ISSUE THREAD

**Issue by grepory** [waffleio/waffle.io#3224] opened 2017-08-02 18:28 UTC
Waffle currently has somewhat special states: "work started" and "new collaborator PRs". For us, these map to "in progress" and "ready for review". I'm trying to find a way to track the time that we're spending in those two states for each of our issues.

This is useful, because it allows me to track things like "issue point estimation" and "time until completion" as well as trying to find out if and why issues are staying in review for extended periods of time.

Having these metrics would be pretty amazing. Please let me know if I can do anything to help or if you have any other questions! Thanks so much! We love waffle.

**Comment by grepory** [comment] 2017-08-02 18:35
I think this is a variation of / duplicate of #287.

**Comment by homeyer** [comment] 2017-11-30 23:26
Yep, closing this as a duplicate of https://github.com/waffleio/waffle.io/issues/1574, something we'd love to see too!

**Closed by homeyer** 2017-11-30 23:26 UTC
