### ISSUE TITLE
AA user, I can easily move groups of waffle cards

### ISSUE THREAD

**Issue by pattscotton** [waffleio/waffle.io#1941] opened 2015-06-03 21:31 UTC
moving cards one by one to prioritize a column of issues is too time consuming.

**Comment by kellihsf** [comment] 2016-04-26 18:49
closing this as a duplicate of [#2107](https://github.com/waffleio/waffle.io/issues/2107). Thanks!

**Closed** 2016-04-26 18:49 UTC
Labels: duplicate
