### ISSUE TITLE
Add ability to move issues between repositories

### ISSUE THREAD

**Issue by brucecrevensten** [waffleio/waffle.io#2044] opened 2015-08-08 20:21 UTC
When using multirepo boards, sometimes issues are added to the wrong repo.  It'd be convenient if you could move the issue to another repo in the same spot you can assign labels, etc.

Moving the GH issue would be what [this tool](https://github-issue-mover.appspot.com) already does.

**Comment by pattscotton** [comment] 2015-08-24 20:35
+1

**Comment by Croydon** [comment] 2015-08-26 20:29
+1

**Comment by nokout** [comment] 2015-09-03 13:11
:+1:

**Comment by mbroadst** [comment] 2015-10-28 15:37
+1

**Comment by oferb1** [comment] 2015-10-28 15:38
+1

**Comment by hlm** [comment] 2015-11-11 14:58
+1

**Comment by damyanmp** [comment] 2015-12-16 22:39
+1

**Comment by thebho** [comment] 2015-12-18 20:36
+1

**Comment by cjsaylor** [comment] 2016-02-12 14:18
:+1:

**Comment by rmharrison** [comment] 2016-03-25 20:53
:+1:

**Comment by lindenle** [comment] 2016-05-04 21:29
:+1:

**Comment by SimonMBPam** [comment] 2016-06-03 00:18
+1

**Comment by markpollack** [comment] 2016-11-04 20:11
+1

**Comment by kellihsf** [comment] 2016-11-21 16:53
closing this as a duplicate of [#1729](https://github.com/waffleio/waffle.io/issues/1729)

**Closed** 2016-11-21 16:54 UTC
Labels: customer requested, duplicate, PM
