### ISSUE TITLE
Filter assign to by collaborators

### ISSUE THREAD

**Issue by dapacheco** [waffleio/waffle.io#3010] opened 2017-03-02 10:26 UTC
When assigning an issue, due to the number of people in our organisation (over 1700), there is a noticeable delay before results are displayed.

This delay is incurred every time you want to assign an issue. It can be verified by looking at the network requests when the button is pressed.

Would it be possible to configure the board to use the collaborators API instead as that would limit it to just those working on a given repo. Or would it be possible to cache this data such that it's only done once per session?

**Comment by homeyer** [comment] 2017-03-07 00:01
We looked into switching to use collaborators, and realized it would be limiting the available assignees to less than what GitHub allows.

The requests are being cached by the browser per source (the request is still made, but a 2ms response vs 300ms on initial fetch). It seems like the problem is rendering hundreds of assignees. 

To fix:
- [ ] use infinite scrolling plugin to only render what's visible, like we do for cards in a column.

**Comment by homeyer** [comment] 2017-06-09 16:09
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Closed** 2017-06-09 16:10 UTC
