### ISSUE TITLE
Add 'comment and close' button in issues

### ISSUE THREAD

**Issue by ajoslin** [waffleio/waffle.io#896] opened 2014-04-30 19:56 UTC
I often want to comment and close something.  I've started using the waffle issue view and comment modal, but closing my issue isn't as easy as it could be.  I have to hide the issue modal and drag my issue to Completed to close it.

It would be nice to have the same buttons as GH in the waffle issue thread view.

**Comment by ashumz** [comment] 2015-02-04 06:13
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/712840651)

"The "Close and comment" button in Github issues interface, feels good and makes sense. Would it be nice to have it in Waffle too?"

**Comment by pjf** [comment] 2015-05-22 08:14
+1 so hard. I have enough columns that the "closed" column is often off the screen now, so this would be perfect.

**Comment by tobalsgithub** [comment] 2015-08-31 16:35
+1

**Comment by amontalenti** [comment] 2015-09-04 18:17
+1

**Comment by tophersimon** [comment] 2015-09-09 19:16
+1

**Comment by koszcz** [comment] 2015-09-28 14:58
+1

**Comment by tobalsgithub** [comment] 2015-11-06 20:39
Our "Done" column is also off the screen. Would really appreciate a close and comment button.

**Comment by homeyer** [comment] 2017-06-09 22:14
duplicate of #828

**Closed** 2017-06-09 22:14 UTC
Labels: customer requested, detail view
