### ISSUE TITLE
Allow renaming projects

### ISSUE THREAD

**Issue by umarniz** [waffleio/waffle.io#3238] opened 2017-08-09 16:38 UTC
This issue was initially a duplicate of #2074 but now is a feature request to allow renaming projects.

All our project boards are multi-repository and the project name being the same as the repository it was originally created with makes it extremely confusing.

**Comment by umarniz** [comment] 2017-08-09 16:42
In our team we have around 20 repositories actively worked on each month and a team that is split by product, platform and role. This means we need different projects for different needs (Mobile, Backend, Product, CI, Company Wide, etc). 

It would be great if I don't need to make a new repository for each team and can create these projects directly in waffle.io and also renaming existing projects so they don't have the same name as the repo from which they are created.

**Comment by kellihsf** [comment] 2017-09-11 22:29
related: [#2604](https://github.com/waffleio/waffle.io/issues/2604)

**Comment by kellihsf** [comment] 2018-08-24 18:02
closing this as a duplicate of #2074

**Closed by kellihsf** 2018-08-24 18:02 UTC
Labels: customer requested, duplicate, idea
