### ISSUE TITLE
Redirect users to a board that has the repo as a secondary source

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2424] opened 2016-03-03 00:43 UTC
If you navigate to a repo (e.g., waffle.io/owner/repo), but owner/repo exists on a project already as a secondary source, we should prompt the user to go the primary board.

[customer requested](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/2032811511)

**Comment by burtonjc** [comment] 2017-07-10 15:43
Closing this as a duplicate of https://github.com/waffleio/waffle.io/issues/1526

**Closed by burtonjc** 2017-07-10 15:43 UTC
Labels: customer requested, duplicate, idea, PM
