### ISSUE TITLE
Add label directly from the board

### ISSUE THREAD

**Issue by cmilr** [waffleio/waffle.io#1928] opened 2015-05-25 06:57 UTC
It would be nice to be able to add labels to cards directly from the board, instead of having to click through to the card.

**Comment by PatrickDattilio** [comment] 2015-06-02 01:49
+1
A dropdown (like assigning a user) in the bottom left corner  would be perfect

**Comment by cbobbett** [comment] 2015-08-05 22:32
+1. 
I want to change a label assignment as easily as I can change sizing (directly from card on board).

**Comment by zbjornson** [comment] 2016-02-07 21:57
+1

**Comment by sibson** [comment] 2016-02-12 04:29
+1

**Comment by lindenle** [comment] 2016-05-04 21:30
:+1: I would also like to see the ability to add the label to all repos for a board that spans multiple repos.

**Comment by shaharmor** [comment] 2016-05-24 09:18
+1

**Comment by kellihsf** [comment] 2018-08-15 18:55
closing as duplicate of [#625](https://waffle.io/waffleio/waffle.io/cards/53440db124ceb40200d90f5c)

**Closed** 2018-08-15 18:56 UTC
Labels: customer requested, duplicate, idea
