### ISSUE TITLE
Filter by NOT a certain label

### ISSUE THREAD

**Issue by dzhenko** [waffleio/waffle.io#1799] opened 2015-03-10 15:11 UTC
When filtering issues, it would be nice to have a NOT check box - for example I want to see all issues, that do not have a current label.

**Comment by ashumz** [comment] 2015-03-10 19:38
Hi @dzhenko, 

Thanks for the request! Are you specifically requesting the ability to filter for unlabeled issues? Or do you also want to be able to search for all issues with do not have a single label, but have any other label (or no label)? 

Thanks! 

Ashley

**Comment by dzhenko** [comment] 2015-03-11 08:29
Hi Ashley,

More like a NOT button - for example I want to see all issues, which **don't have** a certain label or milestone.

Thanks!

Dzhenko

**Comment by CodeMan99** [comment] 2015-04-04 04:52
A simple solution would be to have a "Select All" checkbox and then allow users to selectively uncheck the labels they don't want to see.

**Comment by CodeMan99** [comment] 2015-04-04 04:57
This card seems to be a duplicate of #1045

**Comment by conklinbd** [comment] 2015-04-24 16:17
+1

**Comment by chmac** [comment] 2015-06-01 17:46
:+1:

I'd like to see the ability to create negative filters. For example, to filter by "not assigned to X", so I can see all other tickets. I can create that by choosing all other users and leaving one unchecked, but that's cumbersome, and would get really tiresome with a team of any size.

**Comment by dzhenko** [comment] 2015-06-02 07:28
@CodeMan99 not really - I was talking about something more general - NOT with milestone, NOT assigned to ... just a global not filter. The ticket #1045 is referring only about labels.

**Comment by trapridge** [comment] 2015-06-17 13:36
+1

**Comment by wjrogers** [comment] 2015-11-17 19:30
We could really use this feature for sources, also. We want to be able to exclude a specific repository's issues but see all others.

**Comment by pdpinch** [comment] 2015-11-18 14:00
+1

**Comment by ljhendrickson** [comment] 2016-02-08 19:06
+1

**Comment by kylegifford** [comment] 2016-04-20 17:50
+1

**Comment by jf1978** [comment] 2016-09-08 14:34
+1

**Comment by nsfyn55** [comment] 2016-12-14 16:14
+1

**Comment by mnieber** [comment] 2017-01-13 12:09
+1. 

This missing feature make it hard to keep overview of the backlog. Short term stories are mixed with issues we will be tackling in one year from now, very confusing.

**Comment by superkhau** [comment] 2017-04-05 19:04
Would like to filter by NOT label so we don't have to artificially add labels in order to only show a subset.

**Comment by davidBBC** [comment] 2017-08-07 20:21
+1

**Comment by RickCardoso** [comment] 2018-01-15 22:59
+1

**Comment by Kralizek** [comment] 2018-03-14 09:47
+1

**Comment by mberlanda** [comment] 2018-03-16 09:19
+1

**Comment by thechori** [comment] 2018-04-12 03:16
+1

**Comment by phaistonian** [comment] 2018-05-10 09:18
+1

**Comment by brockhicks** [comment] 2018-05-11 23:00
+1

I would also like to be able to search for something that does not have a label or project. so for example i could search `is:issue is:open label:bug project:none`

**Comment by at-lainguyen** [comment] 2018-06-15 02:49
+1

**Comment by cluesque** [comment] 2018-06-20 03:56
+1

**Comment by carlosisdanger** [comment] 2018-06-20 04:00
+1

**Comment by rolpoe** [comment] 2018-06-20 13:55
+1

**Comment by Everoli** [comment] 2018-06-20 13:57
+1

**Comment by tylerjustinfisher** [comment] 2018-07-04 17:32
+1

**Comment by ivictbor** [comment] 2018-07-12 14:16
+1

**Closed** 2018-07-23 17:21 UTC
Labels: customer requested, staging1, waffle:needs review

**Comment by kellihsf** [comment] 2018-07-24 15:55
Hi all, 👋

You are now able to filter by NOT a certain label in Waffle. Check out the gif below to see how it works or try it out on your own board! 

![exclude_label_filters](https://user-images.githubusercontent.com/4775572/43150583-7e30eade-8f27-11e8-9af1-1bc69795f27b.gif)
