### ISSUE TITLE
Make waffle card urls bound to the GH issue number

### ISSUE THREAD

**Issue by elia** [waffleio/waffle.io#1904] opened 2015-05-11 10:53 UTC
That would be really convenient as the urls would become really predictable.

There's probably the case of multirepo boards which could maybe use an id in the form of <repo-name>-<issue-id> or fallback to the current system (which I suppose are the internal db ids)

**Comment by niemela** [comment] 2016-01-14 02:40
+1

**Comment by kellihsf** [comment] 2018-08-15 19:05
closing as a duplicate of [#1694](https://waffle.io/waffleio/waffle.io/cards/54b421ab579e3b020011ef95)

**Closed by kellihsf** 2018-08-15 19:05 UTC
Labels: customer requested, idea
