### ISSUE TITLE
Images in "Enter Card Description"/"Comments"

### ISSUE THREAD

**Issue by PMmike** [waffleio/waffle.io#1872] opened 2015-04-15 15:15 UTC
The ability to place an image in here would really help when trying to explain things to developers

**Comment by CodeMan99** [comment] 2015-04-17 20:23
@PMmike While I agree, nothing is stopping you from using a little [github flavored markdown](https://help.github.com/articles/github-flavored-markdown/) and an image hosting site (or even just a network drive that both you and the developers mount the same way).

**Comment by mattfletcher** [comment] 2015-07-01 13:07
#846

**Comment by kellihsf** [comment] 2016-04-26 18:45
closing this as a duplicate of [#846](https://github.com/waffleio/waffle.io/issues/846). Thanks!

**Closed** 2016-04-26 18:45 UTC
Labels: duplicate
