### ISSUE TITLE
Filter to see all issues not having a specific label

### ISSUE THREAD

**Issue by adamralph** [waffleio/waffle.io#2546] opened 2016-05-10 10:39 UTC
Initially, I wouldn't even need a UI for this. I'd be happy if I could just manipulate the URL.

E.g. to see all issues with the "API" label, the URL is:

https://waffle.io/waffleio/waffle.io?label=API

to see all issues _without_ the "API" label, the URL could be:

https://waffle.io/waffleio/waffle.io?-label=API

**Comment by kevinkuszyk** [comment] 2016-05-23 09:11
Big +1 from me for this one.  I was talking to @homeyer it in Amsterdam recently.

Possible dupe of #1045?

**Comment by homeyer** [comment] 2017-06-09 19:12
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Closed** 2017-06-09 19:12 UTC
Labels: customer requested, feedback lab

**Comment by adamralph** [comment] 2017-06-21 09:19
What about in 6 months time? Will you go back through the closed issues and pick up stuff you didn't have time to do before? Or is this issue now effectively a "won't fix"?

**Comment by adamralph** [comment] 2017-06-21 09:24
Note that, in addition to myself, 6 other people have added a 👍 to this issue so it's clearly of value.

Even if this isn't a priority now, closing it seems inappropriate. This way, I suspect it will never get done unless someone else has the same idea and raises it again. Or I just raise it again. But then I guess you'll just close that new issue?

Generally: closing an issue sends the message that it is either:

- Done
- Will not be done.

If the issue has value, but is not a priority now, closing seems like the wrong thing to do. It should remain in the backlog, and that backlog should be managed in an appropriate way which allows you to concentrate on the most important things first.

**Comment by homeyer** [comment] 2017-06-21 21:27
Hey @adamralph - my apologies on this one, I should have marked it as a duplicate and linked it to https://github.com/waffleio/waffle.io/issues/1799 (in `planned`).

You're right, closing an issue should mean `done` or `won't fix`. Our goal is to clean up some of our large backlog of things we don't see as fitting with where Waffle is going, thanks for shouting out when we oversteer.

**Comment by adamralph** [comment] 2017-06-22 09:17
@homeyer thanks for the response. Marking this as a duplicate of #1799 and closing it makes sense.

> You're right, closing an issue should mean done or won't fix. Our goal is to clean up some of our large backlog of things we don't see as fitting with where Waffle is going

The comment made when closing this issue, and what is written in the blog post seems to contradict this. I.e. you are going close issues even if they have value, but you don't see yourself getting to them soon.
