### ISSUE TITLE
Support moving issues between repos

### ISSUE THREAD

**Issue by samdeane** [waffleio/waffle.io#1226] opened 2014-07-23 10:33 UTC
It would be great if your UI supported moving an issue between repos. 

I realise that Github doesn't support it, but you could fake it by doing the tedious manual process that we have to do by hand when we make an issue in the wrong repo (make new one, copy info across, close old one). You could also tag the closed issue with something extra so that it doesn't show up in the Done column.

**Comment by wimpers** [comment] 2016-11-17 09:52
+1

**Comment by kellihsf** [comment] 2016-11-21 16:49
closing this as a duplicate of [#2044](https://github.com/waffleio/waffle.io/issues/2044)

**Closed** 2016-11-21 16:50 UTC
Labels: customer requested, duplicate, idea
