### ISSUE TITLE
fix ranking for cards

### ISSUE THREAD

**Issue by jaymedavis** [waffleio/waffle.io#1307] opened 2014-08-12 19:40 UTC
to replicate:

1). filtered board
2). added new issue (matched filter)
3) in GitHub, change label to “ready"
4) refresh board, new issue appears at top of ready column with no rank (correct)
5) dragged to top of next column
6) appeared at bottom instead of top

i'm not able to replicate this on 3/3-ashley

**Comment by agibson22** [comment] 2015-01-05 13:55
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/655755994)

**Comment by ashumz** [comment] 2015-01-23 21:57
The fix for this has been broken down into tasks in our private app repo, to be pulled after we release on-premises work (see app#629)

Leaving this card open for users to reference/report any additional issues.

**Comment by ashumz** [comment] 2015-01-23 22:17
[user report](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/686301915)

**Comment by mweint** [comment] 2015-01-23 22:17
+1

**Comment by ashumz** [comment] 2015-02-04 21:54
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/716270390)

**Comment by nappels** [comment] 2015-02-11 21:39
+1

**Comment by nappels** [comment] 2015-02-11 21:42
I've also noticed that even after dragging a card to a different column, which I though reset ranking, does not fix the problem. I thought that by creating the issue in github, moving it over a column in waffle, I could then be free to move it where I want, but this is not the case.

**Comment by jaymedavis** [comment] 2015-02-11 22:58
If you do not have any filters selected and you drag over to a new column, it should reset ranking for you. If filtering is still on and whatever the bug is is still present, that will not fix it.

**Comment by caramev** [comment] 2015-02-12 00:33
+1

On my team we only use filtered boards since we are a large group sharing one repo. Reordering doesn't work at all in the backlog. Being able to stack rank was one of the primary reasons we are trying Waffle. Please fix!

**Comment by ashumz** [comment] 2015-02-12 19:37
[+1](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/726220639)

**Comment by jpirkey** [comment] 2015-02-17 18:35
+1

**Comment by brianellin** [comment] 2015-02-18 17:50
+1 - proper ordering of columns is key to our team's workflow and the primary reason we're using waffle. this is a big problem for us.

**Comment by JeffLowe** [comment] 2015-02-24 14:22
Just wanted to express how critical the ability to reprioritize filtered tickets is to my team. We were just about to pull the trigger and move to Waffle, but have now paused until I determine if this gets resolved.

**Comment by ashumz** [comment] 2015-02-26 22:45
+1 from #1770 (closed as duplicate)

**Comment by jkmangan** [comment] 2015-02-27 22:24
+1. This is making it impossible to set priorities for our team.... please fix!

**Comment by brianellin** [comment] 2015-02-27 22:27
Could someone from the Waffle team comment on the status and priority of fixing this? We'd love to continue using Waffle, but will be looking for alternatives if this basic functionality isn't fixed soon. Thank you.

**Comment by ashumz** [comment] 2015-03-04 22:29
Hi @brianellin (and everyone subscribed to this issue!),

We've just bumped this up in priority (into our immediate backlog), but our team is working hard currently to ship an on-premises version of Waffle through the end of the month. Our next priority is to redesign the way that ranking works in a way that solves all of the reported issues. 

For everyone following this issue, it would be very helpful for us to have you include replication steps for the issues you are running into  (if you haven't already) as we define the best route for changing the ranking infrastructure. This will help us ensure that our changes resolve all of the problems you're encountering as quickly as possible.

Thanks for being patient with us! We promise we'll fix it and we feel your frustration! 

Ashley

**Comment by ehg** [comment] 2015-04-02 07:39
We were interested in using Waffle, but this issue is stopping us from doing so. 

Steps to reproduce:

1. Filter by milestone(s)
2. Reorder a card
3. Refresh
4. Order lost

**Comment by ashumz** [comment] 2015-04-02 15:37
+1 User report from #1845: 
"Most of the time, when I try to reorder cards and have filters on (I often work with just things assigned to me or noone), reordering works far from reliable:

- some times after dropping a card it lands somewhere at the end of the column, instead at place I've dropped it
- some times, it appears to be dropped correctly, but after page refresh it shows up in other position in the column"

**Comment by bmonetti** [comment] 2015-04-06 21:23
Experiencing same issue described in #1845 making Waffle unusable for us.

**Comment by ashumz** [comment] 2015-04-13 21:35
Just an update on this: we've moved this into our Ready queue for work within the next 2 weeks. Thanks to everyone who has shared their reports. We're working to get all the quirks worked out as soon as possible!

**Comment by basicNew** [comment] 2015-04-27 16:51
Hi, @ashumz! Any news news on this? This is a workflow-killer for me :(

**Comment by pretentiousgit** [comment] 2015-04-30 16:18
+1 this just obliterated my stacks for the day, and my junior is skipping tickets 'cause they never see 'em.

**Comment by klawsonr** [comment] 2015-05-13 22:05
+1 this is a huge problem for my company and looking for other options at the moment.  any update on the timeline for this? 
similar issue is having to drag items all the way up a column. if you can jump to a location (top of column), that would also help.

**Comment by kintso** [comment] 2015-05-21 13:31
+1

**Comment by kintso** [comment] 2015-05-21 13:32
Would you have a timeline on this? The issue was opened 9 months ago and it is something preventing us to switch to Waffle.

**Comment by bmonetti** [comment] 2015-05-26 01:38
Bumping this.  We have been expecting this to be fixed based on this comment: https://github.com/waffleio/waffle.io/issues/1307#issuecomment-92508180  

As described by many people above, this bug is making Waffle unusable for us, and we will be switching services if this is not fixed asap.

**Comment by MFDW** [comment] 2015-06-19 07:43
+1

**Comment by homeyer** [comment] 2015-07-07 22:08
A few more details - if you drag cards rapidly from one column to another, the column API endpoint and realtime updates can't stay in sync, so the whole column can get out of whack.

**Comment by kevinohara80** [comment] 2015-08-10 18:42
>  if you drag cards rapidly from one column to another, the column API endpoint and realtime updates can't stay in sync

@homeyer I don't mean to be a back-seat driver, but have you looked into implementing true operational transforms? 

Resources....

http://operational-transformation.github.io/index.html
http://sharejs.org/

**Comment by MFDW** [comment] 2015-08-21 15:26
I've noticed this happens ~90% of the time when moving a card to the top of a column. And happens ~<50% of the time when moving a card anywhere else in a column.
If I want a card at the top I've gotten into the habit of moving it into 2nd place in the new column then moving the 1st place card into 2nd place, bumping the original card I wanted to move into 1st place.

**Comment by jedmccaleb** [comment] 2015-10-18 15:15
Also when you have a view with multiple repos it doesn't preserve the rank of issues between them. Not sure if this needs its own issue but maybe this can be fixed while you are fixing the other problems.

**Comment by janaka** [comment] 2015-11-04 19:01
I've not noticed this multi repo issue yet (may be It's the one I reported) but I would +1 as I use a multi repo board. There are a few other teams here trying Waffle and also will be using multi repo boards.

**Comment by dokie** [comment] 2015-11-06 09:37
+1

**Closed** 2016-01-06 16:36 UTC
Labels: bug, customer requested, epic, waffle:needs review

**Comment by kylepolich** [comment] 2018-01-05 04:40
+1

**Comment by homeyer** [comment] 2018-01-05 16:03
@kylepolich we shipped this a year ago :). What behavior are you seeing?

**Comment by kylepolich** [comment] 2018-01-05 16:16
@homeyer When I move cards from one column to another, they appear in both places.  If I refresh, the disappear from the destination column.  If I more to "Done" they will stay there, however.

**Comment by homeyer** [comment] 2018-01-05 16:36
Resolved via in-app support, thanks!

**Comment by kylepolich** [comment] 2018-01-05 16:37
Hi @homeyer .  I think its super awesome that you guys were able to find me and reach out with in-app support.  I'm glad to be talking to Kelli now, but its mis-leading to say it's resolved when I am still experiencing the problem and the advice given was in-applicable to my situation.

**Comment by homeyer** [comment] 2018-01-05 16:41
My apologies! Miscommunication on our side, still working on it!

**Comment by kylepolich** [comment] 2018-01-05 16:48
No problem, I'm very impressed by how responsive your team is.

**Comment by kylepolich** [comment] 2018-01-05 17:06
Ok, so for anyone that comes along with a similar issue of Cards mysteriously reverting back to old columns, there is a non-obvious issue to resolve.  Columns must have UNIQUE github labels for some reason.  Feedback I got from support:

> If you click the on the drop down for the column labels, you'll see the green + button there to create a new column label. You can create a "needs review" or "in review" or something relevant for your In Review column. The labels shown in the drop down menu are just the default GitHub labels.

![screen shot 2018-01-05 at 9 00 26 am](https://user-images.githubusercontent.com/1054674/34619600-8a219a50-f1f7-11e7-921f-854bc874744b.png)
