### ISSUE TITLE
add option for milestone to column settings

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io#1283] opened 2014-08-06 20:17 UTC
where you select which label corresponds to which column, being able to select a milestone there also - from [email request](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/mary@waffle.io/conversations/470195972)

**Comment by homeyer** [comment] 2015-03-27 14:58
closing as duplicate of #1414

**Closed by homeyer** 2015-03-27 14:59 UTC
Labels: customer requested
