### ISSUE TITLE
Color cards based on repository

### ISSUE THREAD

**Issue by soltveit** [waffleio/waffle.io#1273] opened 2014-08-05 08:54 UTC

**Comment by RickMohr** [comment] 2015-03-11 22:09
+1 would help a lot.

**Comment by ehlersd** [comment] 2015-03-11 22:11
+1

**Comment by mrmechko** [comment] 2015-06-18 18:50
+1

**Comment by rossjones** [comment] 2015-09-24 15:58
Yup, this would make out backlog MUCH more manageable, otherwise it's hard to see work out which repo the issue is from.  +10

**Comment by charlesccmon** [comment] 2016-03-08 20:51
+1

**Comment by nathanjones** [comment] 2016-10-04 19:36
+1

**Comment by dwowens** [comment] 2017-01-24 20:41
+10

**Comment by homeyer** [comment] 2017-06-09 20:57
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208

**Closed** 2017-06-09 20:58 UTC
Labels: customer requested, detail view
