### ISSUE TITLE
Wafflebot does not move issues to "Collaborator PR"

### ISSUE THREAD

**Issue by burnhamrobertp** [waffleio/waffle.io#3195] opened 2017-07-05 13:07 UTC
When creating a pull request linked to an issue via `connects to ...`, the issue does not get pulled to the designated "New Collaborator PR" column. Our "New Collaborator PR" column is "Code Review." The PR itself gets the "code review" label but the issue does not. The PR gets linked to the issue and is appropriately "connected" to it.

![image](https://user-images.githubusercontent.com/231052/27865841-c11fc33a-6159-11e7-93a8-e9f22f848e0d.png)

All in all, it appears the issue is that swimlane labels for PRs are not appropriately given priority over swimlane labels for issues.

![image](https://user-images.githubusercontent.com/231052/27865758-6d2c8d08-6159-11e7-8f12-c01349489aae.png)
![image](https://user-images.githubusercontent.com/231052/27865806-99c53e96-6159-11e7-9757-b3efbfba7a5c.png)

Swimlane configuration:
![image](https://user-images.githubusercontent.com/231052/27865675-18a98c54-6159-11e7-935a-1157c3cbd0f5.png)

**Comment by homeyer** [comment] 2017-07-05 23:36
The best we can do when using Waffle's `connect` keywords is move the connected issue to the `Work Started` column, and move the PR  to the same point. Reason being is that using `fixes`/`closes` will move it to the `New Collaborator PRs` column, because the PR actually resolves the issue and GitHub will close the issue when the PR is merged, so we treat that as ready for review. Just connecting a PR doesn't mean the issue is ready for review.

**Comment by harkenn** [comment] 2017-07-06 13:18
There is already an automated method for moving an issue to the `Work Started` column, though, why is there a need to provide an alternative way for achieving that same approach? If the notion is to provide as much functionality to as wide a customer base as possible, exactly how many development groups are you seeing use PRs to "mark" that work has started? Its not a likely approach to development for lots of obvious reasons.

All of this comes back to the issue that QA looks through integrated PRs AFTER they've been merged. I can't close issues automatically (using `fixes` or `closes`) because its too easy for QA to miss testing issues if they're moved into `Done` once the PR gets merged. So PRs have to use `connect`. Going back to the first couple of sentences, why would anyone use PRs just to mark that work is completed? It seems obvious (literally to everyone in my org's development group, 9 developers) that `connect` aught to move the issue (and connected PR) to `New Collaborator PR` and after the PR is closed, leave it there without moving it further.

**Comment by homeyer** [comment] 2017-07-06 23:24
If Waffle allowed you to have more columns after `Done` would that change how your team worked? E.g, `Done` becomes `Ready for QA` and then there's `Accepted` and `Deployed` after?

**Comment by harkenn** [comment] 2017-07-07 13:54
It would be an option, but having to use `closes` or `fixes` means issues are closed before they're actually tested and confirmed fixed, which is still technically not right.

**Comment by kellihsf** [comment] 2018-08-24 18:17
hi @burnhamrobertp,

We haven't seen any activity on this card from the rest of the Waffle user base. We are closing it for now as we prioritize and work on other more highly requested features/integrations. Thank you! :)

**Closed by kellihsf** 2018-08-24 18:17 UTC
Labels: idea
