### ISSUE TITLE
Investigate: Labels deleted by authenticated user for no reason

### ISSUE THREAD

**Issue by jfrazelle** [waffleio/waffle.io#1761] opened 2015-02-11 22:35 UTC
There seems to be some sort of a race somewhere.

We have a bot that applies labels on PRs from the Github webhooks. However when a user with permissions is authenticated with waffle, it deletes the label on their behalf. Without the user actually deleting it.

See https://github.com/docker/docker/pull/10710

our bot GordonTheTurtle applies the label at the same time the autenticated user @dmcgowan "removes it" except @dmcgowan didn't do anything or intend to remove it. Somehow waffle removes it because he is authed.

This has happened numerous times with numerous different authed users and the only solution is un-authing waffle. Or adding a sleep to the bot.

cc @crosbymichael @icecrime @tiborvass

**Comment by ashumz** [comment] 2015-02-12 21:56
Hi @jfrazelle, 

Thanks for reporting this. Our team will take a look at the issue and let you know what we find. 

Ashley

**Comment by marydavis** [comment] 2015-02-18 15:33
Hi @jfrazelle, 

We are currently trying to replicate this issue so we can solve it. Is there a reason why you have numbers in front of the labels you use for your columns? 

Thanks,

Mary

**Comment by jfrazelle** [comment] 2015-02-18 16:13
The numbers represent steps in our process

On Wednesday, February 18, 2015, Mary <notifications@github.com> wrote:

> Hi @jfrazelle <https://github.com/jfrazelle>,
>
> We are currently trying to replicate this issue so we can solve it. Is
> there a reason why you have numbers in front of the labels you use for your
> columns?
>
> Thanks,
>
> Mary
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/waffleio/waffle.io/issues/1761#issuecomment-74884004>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment] 2015-02-18 16:18
We are also seeing weird behavior where if I submit a patch fixing an issue,
I am automatically assigned to that issue by an authed user. Here's an
example:

https://github.com/docker/docker/issues/10832

On Wednesday, February 18, 2015, Jessica Frazelle <me@jessfraz.com> wrote:

> The numbers represent steps in our process
>
> On Wednesday, February 18, 2015, Mary <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Hi @jfrazelle <https://github.com/jfrazelle>,
>>
>> We are currently trying to replicate this issue so we can solve it. Is
>> there a reason why you have numbers in front of the labels you use for your
>> columns?
>>
>> Thanks,
>>
>> Mary
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/waffleio/waffle.io/issues/1761#issuecomment-74884004>
>> .
>>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>
>

-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by marydavis** [comment] 2015-02-18 20:17
@jfrazelle, 

Thanks for the quick response! I believe some of Waffle’s automatic work tracking is what is causing the actions listed. 

In the column settings, you can select which column Pull Requests go into when created which may have be causing the column label being removed when your bot added it. To fix this, you can turn Collaborator and Non-Collaborator PR start off on the columns.

In regards to you being auto-assigned, whenever someone uses GitHub ‘closing keywords’ we automatically assign you to the issue you are closing. 

To learn more how to use Waffle’s automatic work tracking to your benefit or how to avoid it if you would like, check out our full article here: https://github.com/waffleio/waffle.io/wiki/Pull-Requests-&-Automatic-Work-Tracking

**Comment by jfrazelle** [comment] 2015-03-09 17:24
Also now we are seeing PRs being reopened https://github.com/docker/docker/pull/10365#issuecomment-77898992

**Comment by frogandcode** [comment] 2015-03-17 17:17
Hi @marydavis, we're seeing this too (and don't have any webhooks in place):

![image](https://cloud.githubusercontent.com/assets/12514/6693219/c58ef5ce-cca7-11e4-98d2-d3140f9e693a.png)

Here's our column setup in case that's helpful for debugging:

![image](https://cloud.githubusercontent.com/assets/12514/6693233/d9eacd90-cca7-11e4-89e9-46c4c324cb5b.png)

The one thing we have in play that's a bit unusual is that we removed the _Done_ column.

**Comment by vieux** [comment] 2015-03-17 17:43
Same here, many issues, I was moving stuff around in `docker/swarm` and this PR on `docker/docker` got closed https://github.com/docker/docker/pull/10283

**Comment by ashumz** [comment] 2015-03-23 14:54
@frogandcode and @vieux, 

Wanted to give you a quick update. We're working on an internal tool right now to help diagnose this issue . Thanks for your patience as we prioritize this issue and try to get it resolved for you as soon as possible. 

Cheers, 

Ashley

**Comment by ashumz** [comment] 2015-03-25 15:12
@frogandcode and @vieux and @jfrazelle,

We introduced some additional logging to help us track this down if it happens again. Unfortunately, without having that in the past, we can't properly diagnose the problem you ran into. If you're willing to give things another go, we should have all information we need to track any potential bugs you're hitting. 

Let us know if you have any questions or if you run into anything else going forward.

Ashley

**Comment by vieux** [comment] 2015-03-25 21:14
Hi @ashumz thanks for investigating this. 

Did you sincerely intend to close this issue ??? -- or is the the bug in waffle :D 

Because the issue is **far** from resolved.

**Comment by burtonjc** [comment] 2015-03-26 14:56
Hi @vieux, sorry for closing this, it was a miscommunication on our end. We just added some additional monitoring around actions Waffle.io takes in GitHub on the behalf of our users. Do you still have some users auth'd with Waffle.io so we can monitor what is going on to cause the behavior you are seeing?

**Comment by burtonjc** [comment] 2015-03-26 23:26
@vieux, @jfrazelle, @frogandcode, I just reviewed all the actions Waffle.io took on behalf of your users in docker/docker for the past 9 hours and nothing is standing out to me as suspicious. Have to you seen any funny behavior in the past day?

**Comment by frogandcode** [comment] 2015-03-27 20:29
Hi Jacob,

For some reason I'm not getting notifications for this issue despite being subscribed to it. Sorry for not chiming in earlier.

I just had someone over here try a pull request (# 2271 - _Fluid shot pages +  full-width header/footer_, I can give you more details to find it if you need them) and we saw the same behavior:

![image](https://cloud.githubusercontent.com/assets/12514/6876481/5215ccb8-d49e-11e4-9c7c-fd4c083c4449.png)

Thanks and good luck!

**Comment by frogandcode** [comment] 2015-03-27 20:31
Same situation with #2272 - _Upgrade to Rails 4.2_.

**Comment by burtonjc** [comment] 2015-03-27 21:12
@frogandcode, which repo is this on?

**Comment by burtonjc** [comment] 2015-03-27 21:36
@frogandcode, I think I see what is going on. It has to do with multiple Waffle.io project (each with different columns) set up with the same repo. I will send you a message through our in app messaging system with more details.

**Comment by ashumz** [comment] 2015-03-30 22:30
@frogandcode and @vieux and @jfrazelle,

The deletion of labels is occurring due to the way one or more of your boards is set up in terms of column labels. If you have primary source repository X, with Y and Z connected, and all of those boards have matching column labels, you're all set! 

The problem occurs when you introduce another repository, repository B, that has repository X connected, but repository B only has, say, 2 columns present in Settings->Columns set up, and is missing the columns for Collaborator PR start (ie: your Needs Review column). When you issue a pull request for repository X, repository B's lack of matching column label for "Collaborator PR Start" results in confusing behavior -- ie: the removing of an issue label by repository B's team member(s).

We have a bit of work to decide on the best way to handle this, but in the meantime, if you make sure that all of your boards that are connected in some way via multirepo in Settings->Sources have the same column labels, you'll be able to avoid the issue. (We can look into this for you on our end now that we have all of the information if you see this behavior in the future.)

If you have unauth'ed Waffle and want to give us another chance, we'll have much more knowledge available for troubleshooting in the future. 

Cheers, 

Ashley

**Closed** 2015-04-01 21:14 UTC
Labels: bug, expedite

**Comment by ashumz** [comment] 2015-04-01 21:17
Closing this issue out for now. If you have questions or want to work with us further on the issue, we're happy to work with you to get things working properly!

Ashley

**Comment by frogandcode** [comment] 2015-04-01 21:20
@ashumz @burtonjc Just replied to your email, following up here as well. I've deleted the boards with duplicate repos (wasn't really using them), hopefully that will solve. I'll let you know if the problem reoccurs. Thanks so much for investigating!
