### ISSUE TITLE
As a user, I can assign a person to my card during the process of creating a new issue

### ISSUE THREAD

**Issue by heyitsolivia** [waffleio/waffle.io#1719] opened 2015-01-23 19:33 UTC
When I create a new issue from within Waffle, I would like to be able to assign a person to that issue in the same dialog. Currently I need to locate the newly created issue on my board before I can assign someone to it.

**Comment by ashumz** [comment] 2015-01-23 22:24
Hi @heyitsolivia!

Thanks for the request! This is a duplicate of issue #1554 (https://waffle.io/waffleio/waffle.io/cards/5453c69c7abdfe69daba5b92)  so I've linked your request to that and will be closing this one out. Please subscribe to that issue for future updates on forward progress. 

Cheers, 

Ashley

**Closed** 2015-01-23 22:24 UTC
Labels: duplicate
